#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install nginx
sed -i "25 i add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
sudo service nginx restart
