#!/usr/bin/env bash
# Using your debugging skills, find out s
# keeping your Ubuntu s Nginx installation from listening on port 80.
# Feel free to install whatever tool you need, start and destroy
# as many containers as you need to debug the issue.
# Then, write a Bash script with the minimum number of
# commands to automate your fix.containerwhat
sudo sed -i 's/8080/80' /etc/nginx/sites-enable/default
sudo service nginx restart
