#!/usr/bin/env bash
#this is the advance task 100 read and cut
echo $BASHPID > /var/run/holbertonscript.pid
trap 'echo I hate the kill command; sudo rm /var/run/hobertonscript.pid' SIGTERM
trap 'echo Y U no love me?!' SIGINT
while true
do
    echo "To infinity and beyond"
done
