#!/usr/bin/env bash
#This script configures a ubuntu server
cp -f /etc/hosts ~/hosts.cpy
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~/hosts.cpy  
echo "8.8.8.8 facebook.com" >> /etc/hosts
cp -f ~/hosts.cpy /etc/hosts
